### ISSUE TITLE
Clojure base project needs to be updated to run with newest Clojure version

### ISSUE THREAD

**Issue by jimkoglerdw** [democracyworks/dw-practical-upcoming-elections#11]
I briefly tried to run the Clojure project when I was interviewing and the project threw an error with the Clojure version I downloaded.  

It doesn't seem like we're interviewing immediately so this is low priority but I wanted to make a note that this will need some attention before it can be used for hiring.

**Comment by gws** [comment]
@jimkoglerdw I wasn't involved in the last hiring round, but I wonder if we can correlate this to a low volume of Clojure applications? :joy:

Fixed in https://github.com/democracyworks/dw-practical-upcoming-elections/commit/bbb8036f1dbee3bec29e50a0fe2b3bce9ff0884f

cc @katrinamariehh

**Comment by gws** [comment]
Almost certainly related to #9
